name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - a01-broken-access-control/cwe-22-path-traversal-flask
    steps:
      - uses: actions/checkout@v5

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Installer uv
        run: python -m pip install --upgrade uv

      - name: Créer un uv venv and installer les dépendances
        working-directory: ${{ matrix.project }}
        run: |
          uv venv
          uv sync --dev

      - name: Exécuter les tests
        working-directory: ${{ matrix.project }}
        run: uv run pytest -vv

